<?PHP
echo "
</TABLE>
<TABLE cellSpacing=0 cellPadding=0 width=1004 align=center border=0>
<TBODY>
<TR>
<TD bgColor=#e5e5e5>&nbsp;</TD>
<TD width=764>
	<TABLE cellSpacing=0 cellPadding=0 width=764 border=0>
	<TBODY>
	<TR>
	<TD width=12><IMG height=69 src='images/bottom_01.jpg' width=12></TD>
	<TD background=images/bottom_bg.jpg>
		<TABLE cellSpacing=0 cellPadding=0 width=739 border=0>
		<TBODY>
		<TR>
		<TD height=8></TD></TR>
		<TR>
		<TD height=56>
			<TABLE cellSpacing=0 cellPadding=0 width='100%' align=center border=0>
			<TBODY>
			<TR>
			<TD vAlign=center width=461>Copyright&copy;2012-2015 by ".$config_title2." Corporation. All rights reserved.</TD>
			</TR>
			</TBODY>
			</TABLE>
		</TD>
		</TR>
		<TR>
		<TD height=4></TD>
		</TR>
		</TBODY>
		</TABLE>
	</TD>
	<TD width=13><IMG height=69 src='images/bottom_02.jpg' width=13></TD>
	</TR>
	</TBODY>
	</TABLE>
</TD>
<TD bgColor=#e5e5e5>&nbsp;</TD>
</TR>
</TBODY>
</TABLE>
</BODY>
</HTML>";
?>