<?PHP
echo "
<META http-equiv=Content-Type content='text/html; charset=gb2312'>
<STYLE type=text/css>BODY {
	MARGIN: 0px; BACKGROUND-COLOR: #ffffff
}
.txt {
	FONT-WEIGHT: bold; FONT-SIZE: 12px; COLOR: #2a4870; FONT-FAMILY: Verdana
}
.txt2 {
	FONT-WEIGHT: bold; FONT-SIZE: 12px; COLOR: #24a9ed; FONT-FAMILY: Verdana
}
A:link {
	FONT-SIZE: 12px; COLOR: #2a4870; FONT-FAMILY: Verdana; TEXT-DECORATION: none
}
A:visited {
	FONT-SIZE: 12px; COLOR: #2a4870; FONT-FAMILY: Verdana; TEXT-DECORATION: none
}
A:active {
	FONT-SIZE: 12px; COLOR: #2a4870; FONT-FAMILY: Verdana; TEXT-DECORATION: none
}
A:hover {
	FONT-SIZE: 12px; COLOR: #24a9ed; FONT-FAMILY: Verdana; TEXT-DECORATION: underline
}
BODY {
	FONT-SIZE: 12px; FONT-FAMILY: Verdana
}
TD {
	FONT-SIZE: 12px; FONT-FAMILY: Verdana
}
TH {
	FONT-SIZE: 12px; FONT-FAMILY: Verdana
}
#ServerInfo {
	position:absolute;
	left:408px;
	top:230px;
	width:186px;
	height:178px;
	z-index:1;
}
#topswf {
	position:absolute;
	left:0px;
	top:0px;
	width:1004px;
	height:411px;
	z-index:2;
}
#Layer5 {
	Z-INDEX: 3;
	LEFT: 16px;
	WIDTH: 100px;
	POSITION: absolute;
	TOP: 400px;
	HEIGHT: 300px;
}
#Layer6 {
	Z-INDEX: 3;
	LEFT: 889px;
	WIDTH: 100px;
	POSITION: absolute;
	TOP: 400px;
	HEIGHT: 300px;
}
.style1 {
	COLOR: #ffffff
}
</STYLE>
<META content='MSHTML 6.00.2900.2963' name=GENERATOR></HEAD>
<BODY>

<!--¶¥²¿½áÊø-->
<TABLE cellSpacing=0 cellPadding=0 width=1004 align=center border=0>
<TBODY>
<TR>
<TD width='1004' height='302' background=images/logo.jpg></TD>
</TR>
</TBODY>
</TABLE>
<TABLE cellSpacing=0 cellPadding=0 width=1004 align=center border=0>
<TBODY>
<TR>
<TD><IMG src='images/yt_09.jpg'></TD>
<TD><A href='regist.php'><IMG src='images/yt_10.jpg' border=0></A><TD>
<TD><A href='change.php'><IMG src='images/yt_11.jpg' border=0></A></TD>
<TD><A href='".$config_index_url."'><IMG src='images/yt_12.jpg' border=0></TD>
<TD><A href='recall.php'><IMG src='images/yt_13.jpg' border=0></A></TD>
<TD><A href='".$config_bbs_url."' target=_blank><IMG src='images/yt_14.jpg' border=0></A></TD>
<TD><IMG src='images/yt_15.jpg'></TD>
</TR>
</TBODY>
</TABLE>";
?>