<?PHP
echo "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Transitional//EN'>
<HTML><HEAD><TITLE></TITLE>
<META http-equiv=Content-Type content='text/html; charset=gb2312'>
<LINK href='images/user.css' type=text/css rel=stylesheet>
<STYLE type=text/css>
BODY {
BACKGROUND-COLOR: #FFFCF3
}
.style1 {
	COLOR: #0000ff
}
.style2 {
	FONT-SIZE: 16px
}
.style3 {
	COLOR: #ff0000
}
</STYLE>
<BODY bgColor=#ffffff leftMargin=0 topMargin=0 marginheight='0' marginwidth='0'>";
?>